# run gitlab, re-create the container if required
run:
  retry: 2
  tags:
    - shell
  only:
    - master
  when: manual
  interruptible: false
  script:
     # .env file is used because we can't apply environment
     # variables from the GitLab interface here, so re-starting
     # GitLab does not require GitLab running
     - ln -s /opt/config/.env.gitlab ./.env
     - docker info
     - docker images
     - docker-compose up -d

# load the latest image from the docker registry,
# and if neccessary re-create the container
upgrade:
  retry: 2
  tags:
    - shell
  only:
    - master
  when: manual
  interruptible: false
  script:
     # .env file is used because we can't apply environment
     # variables from the GitLab interface here, so re-starting
     # GitLab does not require GitLab running
     - ln -s /opt/config/.env.gitlab ./.env
     - docker info
     - docker images
     - docker-compose pull
     - docker-compose up -d

# stop and tear down containers
down:
  retry: 2
  tags:
    - shell
  only:
    - master
  when: manual
  interruptible: false
  script:
     # .env file is used because we can't apply environment
     # variables from the GitLab interface here, so re-starting
     # GitLab does not require GitLab running
     - ln -s /opt/config/.env.gitlab ./.env
     - docker-compose down

# restart containers
restart:
  retry: 2
  tags:
    - shell
  only:
    - master
  when: manual
  interruptible: false
  script:
     - ln -s /opt/config/.env.gitlab ./.env
     - docker-compose restart

# vim: tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab

