version: '3.5'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: '${GITLAB_HOSTNAME:-git.leo9000.de}'
    environment:
      VIRTUAL_HOST: '${GITLAB_HOSTNAME:-git.leo9000.de},${REGISTRY_HOSTNAME:-docker.leo9000.de}'
      LETSENCRYPT_HOST: '${GITLAB_HOSTNAME:-git.leo9000.de},${REGISTRY_HOSTNAME:-docker.leo9000.de}'
      LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL}'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${GITLAB_HOSTNAME:-git.leo9000.de}'
        gitlab_rails['initial_root_password'] = '${GITLAB_ROOT_PASSWORD}'

        gitlab_rails['time_zone'] = 'Europe/Berlin'
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_display_name'] = 'GitLab | Leopoldina | No Reply'
        gitlab_rails['gitlab_default_can_create_group'] = false
        gitlab_rails['gitlab_username_changing_enabled'] = true
        gitlab_rails['gitlab_email_from'] = '${GITLAB_MAIL_ADDRESS}'
        gitlab_rails['gitlab_email_reply_to'] = '${GITLAB_MAIL_ADDRESS}'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'mail.leo9000.de'
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = '${GITLAB_SMTP_USER_NAME}'
        gitlab_rails['smtp_password'] = '${GITLAB_SMTP_PASSWORD}'
        gitlab_rails['smtp_domain'] = '${GITLAB_HOSTNAME}'
        gitlab_rails['smtp_authentication'] = 'login'
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'

        gitlab_rails['incoming_email_enabled'] = true
        gitlab_rails['incoming_email_address'] = '${GITLAB_MAIL_INCOMING_ADDRESS}'
        gitlab_rails['incoming_email_email'] = '${GITLAB_SMTP_USER_NAME}'
        gitlab_rails['incoming_email_password'] = '${GITLAB_SMTP_PASSWORD}'
        gitlab_rails['incoming_email_host'] = 'mail.leo9000.de'
        gitlab_rails['incoming_email_port'] = 993
        gitlab_rails['incoming_email_ssl'] = true
        gitlab_rails['incoming_email_start_tls'] = false
        gitlab_rails['incoming_email_mailbox_name'] = 'inbox'
        gitlab_rails['incoming_email_idle_timeout'] = 60

        gitlab_rails['backup_keep_time'] = 604800
        gitlab_rails['omniauth_providers'] = [{"name" => "github", "app_id" => "${GITLAB_GH_APP_ID}", "app_secret" => "${GITLAB_GH_APP_SECRET}", "args" => { "scope" => "user:email" }}]

        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['redirect_http_to_https'] = true
        nginx['real_ip_trusted_addresses'] = [ '10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16' ]
        nginx['real_ip_header'] = 'X-Forwarded-For'
        nginx['real_ip_recursive'] = 'on'

        registry_external_url 'https://${REGISTRY_HOSTNAME:-docker.leo9000.de}'
        registry_nginx['listen_port'] = 80
        registry_nginx['listen_https'] = false

        pages_external_url 'https://${GITLAB_HOSTNAME:-git.leo9000.de}'
        pages_nginx['listen_port'] = 80
        pages_nginx['listen_https'] = false
        gitlab_pages['inplace_chroot'] = true

        prometheus_monitoring['enable'] = false
        # Add any other gitlab.rb configuration here, each on its own line
    sysctls:
        # Redis needs some tweaks:
        # https://github.com/docker-library/redis/issues/35
      - net.core.somaxconn=1024
    ports:
      - '22:22'
    volumes:
      - 'config:/etc/gitlab'
      - 'logs:/var/log/gitlab'
      - 'data:/var/opt/gitlab'
      - '/etc/localtime:/etc/localtime:ro'
    networks:
      - proxy-network
      - mail

volumes:
    config:
    logs:
    data:

networks:
  proxy-network:
   name: global-proxy-network
   external: true
  mail:
   name: global-mail-network
   external: true

# vim: tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab

